remote = 'fc600231e3f74d.lhr.life'
owner = 'schemistrylab'
repository = 'item-manager'
contracts_path = './contracts'
dependencies_path = './dep_vendor'

[[contracts]]
name = 'item.created'
language = 'proto3'
status = 'enabled'
majorVersions = {v1 = 'enabled'}

[[dependencies]]
remote = 'fc600231e3f74d.lhr.life'
owner = 'schemistrylab'
repository = 'item-manager'
name = 'item.created'
language = 'proto3'
version = '1.1.0'
