remote = '96cd3ec23705b1.lhr.life'
owner = 'schemistrylab'
repository = 'item-manager'
contracts_path = './contracts'
dependencies_path = './dep_vendor'
contracts = []

[[dependencies]]
remote = '96cd3ec23705b1.lhr.life'
owner = 'schemistrylab'
repository = 'item-manager'
name = 'item.created'
language = 'proto3'
version = '1.1.0'
