Remote = '149ca2b8922cee2283d2daaa8455c9e7.serveo.net'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'avro'

[Modules.List.Versions]
[Modules.List.Versions.v1]
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []
