Remote = '86cd-94-242-171-231.ngrok-free.app'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'proto3'
Status = 'enabled'

[Modules.List.Versions]
[Modules.List.Versions.v1]
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []
