Remote = 'ad5b-62-148-157-185.ngrok-free.app'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'avro'
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []

