Remote = 'dbf4db87131f5ca99c9179f49b9e6868.serveo.net'
Owner = 'schemistrylab'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.created'
Language = 'proto3'
Status = 'enabled'

[Modules.List.Versions]
[Modules.List.Versions.v1]
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []
