remote = 'fb5bc7269d3251efd763bf315d2c6e36.serveo.net'
owner = 'schemistrylab'
repository = 'item-manager'
contracts_path = './contracts'
dependencies_path = './dep_vendor'

[[contracts]]
name = 'item.created'
language = 'proto3'
status = 'enabled'
majorVersions = {v1 = 'enabled'}

[[dependencies]]
remote = 'fb5bc7269d3251efd763bf315d2c6e36.serveo.net'
owner = 'schemistrylab'
repository = 'item-manager'
name = 'item.created'
language = 'proto3'
version = '1.1.0'
