remote = '5c34d9d58ce839a18b56affa1e2fc4a8.serveo.net'
owner = 'schemistrylab'
repository = 'item-manager'
contracts_path = './contracts'
dependencies_path = './dep_vendor'
contracts = []
dependencies = []
