Remote = '11734c65a371c8d08a73e1b29b4fadc6.serveo.net'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'avro'
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []

