Remote = 'a3ce2080dc0628eb030d401974b601f2.serveo.net'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'avro'
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []

