Remote = 'b4ad131d6695b74ffbc367fc3a126124.serveo.net'
Owner = 'yuvbeskrovnyy'
Repository = 'item-manager'

[Modules]
Path = './contracts'

[[Modules.List]]
Name = 'item.changed'
Language = 'avro'
Status = 'enabled'

[Modules.List.Versions]
[Modules.List.Versions.v1]
VersionNumber = '1.0.0'

[Deps]
Path = './dep_vendor'
List = []
