name: Schema check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  use-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint schema
        uses: docker://imbofaker007/schemistry_github_lint
        with:
          token: "Hello from GitHub Actions workflow!"
      - name: Check for breaking changes
        uses: docker://imbofaker007/schemistry_github_break_cheker

      - name: Register schema changes
        uses: docker://imbofaker007/schemistry_github_push
